### ISSUE TITLE
The page says to "click on new web app button" but there isn't one

### ISSUE THREAD

**Issue by datatalking** [pythonanywhere/pythonanywhere_task_helpers#2]
I'm wondering if this is perhaps not exactly a bug but a feature of something that hasn't been done, or was "asserted" to already be done. My current guess is confirming the email, which I haven't received yet as a new user? So there is no button on the left, at the drop down from the right either.

<img width="1440" alt="Screen Shot 2023-02-10 at 12 03 19 PM" src="https://user-images.githubusercontent.com/11813209/218188602-3861a653-15d8-4bc0-8a11-809e9da3020c.png">

If this is the case do you accept PR to add a comment similar to "If you do not see the "New Web App button" you likely haven't clicked the "confirm email" link we sent you via email?

**Comment by gpjt** [comment]
If you go back one step, you'll see that it tells you to click on the "Open web tab" button on the Dashboard -- it looks like you clicked on the "Consoles" page and then on the link to start a MySQL console instead, so the helper text is talking about a different page to the one that you are on.
